import turtle
turtle.bgcolor('pink')
turtle.shape('arrow')
yw=turtle.Turtle()
yw.shape('circle')
yw.left(90)
turtle.right(90)
yw.color('yellow')
turtle.color('green')
turtle.pensize(4)
yw.pensize(2)
turtle.forward(150)
yw.forward(150)
yw.left(90)
turtle.left(90)
yw.forward(75)
turtle.forward(75)
yw.left(90)
turtle.left(90)
yw.color('white')
turtle.color('blue')
yw.forward(150)
turtle.forward(150)


